---
title: "Feature selection"
author: "Nirmal Sitaldin"
date: "9/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Loading libraries}

#Data cleaning & exploration
library(dplyr)
library(magrittr)
library(foreign)
library(tidyverse)
library(moments)
library(EnvStats)
library(xfun)

#Visualization
library(ggplot2)
library(ggpubr)

#Feature selection
library(mlr)
library(spFSR)
url <- "https://cran.r-project.org/src/contrib/Archive/randomForest/randomForest_4.6-12.tar.gz"
#install.packages(url, repos=NULL, type="source") 
library(randomForest)
library(xgboost)
library(deepnet)
library(glmnet)
library(stats)
library(kknn)


```

```{r Data loading / preprocessing}

data <- read.spss("data/SPSS bestand_met schildkliergroepen.sav",
                use.value.label=FALSE, 
                to.data.frame=TRUE)

df <- data %>%
        select(c(1:4), matches("_12"), 49) %>%
        dplyr::rename(Score = 'Schildsymp_12',
                      Profiel = 'sfsgez5')

df$group <- as.numeric(ifelse(df$tsh1 > 0.229 & df$tsh1 < 4.02 &
                              df$ft41 > 11.64 & df$ft41 < 18.01, 1, #Ref group
                       ifelse(df$tsh1 > 4.01 & df$ft41 < 11.65, 2, #OHypo
                       ifelse(df$tsh1 < 0.23 & df$ft41 > 18.00, 3, #OHyper
                       ifelse(df$tsh1 > 4.01 & 
                              df$ft41 > 11.64 & df$ft41 < 18.01, 4, #SHypo
                       ifelse(df$tsh1 < 0.23 &
                              df$ft41 > 11.64 & df$ft41 < 18.01, 5, #SHyper
                       ifelse(df$tsh1 > 0.229 & df$tsh1 < 4.02 &
                              df$ft41 < 12, 6, #IHypo
                       ifelse(df$tsh1 > 0.229 & df$tsh1 < 4.02 &
                              df$ft41 > 18.00, 7, 0#IHyper
                              ))))))))

df2 <- df %>%
        select(matches("_12"), 19)


df2$group <- as.character(df$group)
class(df2$group)

```

```{r Feature selection}
df1 <- read.csv("data/dataframe.csv")

#Train test splitting
sample <- sample(c(TRUE, FALSE), nrow(df1), replace=TRUE, prob=c(0.8,0.2))
train  <- df1[sample, ]
test   <- df1[!sample, ]

df2 <- train %>%
  select(-c(1))

test1 <- test %>%
      select(-c(1))

df2$profiel <- as.character(df2$profiel)
test1$profiel <- as.character(test1$profiel)

```



```{r SPSA}

#Target + pred

task <- makeClassifTask(data = df2,
                target = "profiel")

pred_task <- makeClassifTask(data = test1,
                target = "profiel")

#Classifier

wrapper1 <- makeLearner("classif.randomForest", predict.type = "prob", fix.factors.prediction = TRUE) #RF

wrapper2 <- makeLearner("classif.glmnet", predict.type = "prob", fix.factors.prediction = TRUE) #LR w GLMNet

wrapper3 <- makeLearner("classif.kknn", predict.type = "prob", fix.factors.prediction = TRUE) #KNN

wrapper4 <- makeLearner("classif.svm", predict.type = "prob", fix.factors.prediction = TRUE) #SVM


#Feature selection
set.seed(12)

spsaMod1 <- spFeatureSelection(task = task,
wrapper = wrapper1, measure = multiclass.au1p, iters.max=5,
num.features.selected = 0,
perf.eval.method = "cv", num.cv.folds = 5, num.cores = 8, gain.min = 0.1)

spsaMod2 <- spFeatureSelection(task = task,
wrapper = wrapper2, measure = multiclass.au1p, num.features.selected=0, iters.max=5,
perf.eval.method = "cv", num.cv.folds = 5, num.cores = 8, gain.min = 0.1)

spsaMod3 <- spFeatureSelection(task = task,
wrapper = wrapper3, measure = multiclass.au1p, num.features.selected=0, iters.max=5,
perf.eval.method = "cv", num.cv.folds = 5, num.cores = 8, gain.min = 0.1)

spsaMod4 <- spFeatureSelection(task = task,
wrapper = wrapper4, measure = multiclass.au1p, num.features.selected=0, iters.max=5,
perf.eval.method = "cv", num.cv.folds = 5, num.cores = 8, gain.min = 0.1)

#Best model

modRF <- getBestModel(spsaMod1)
modLR <- getBestModel(spsaMod2)
modKNN <- getBestModel(spsaMod3)
modSVM <- getBestModel(spsaMod4)

#Prediction

predRF <- predict(modRF, task = spsaMod1$task.spfs )
calculateConfusionMatrix( predRF )

predLR <- predict(modLR, task = spsaMod2$task.spfs )
calculateConfusionMatrix( predLR)

predKNN <- predict(modKNN, task = spsaMod3$task.spfs )
calculateConfusionMatrix( predKNN )

predSVM <- predict(modSVM, task = spsaMod4$task.spfs )
calculateConfusionMatrix( predSVM )

#https://rdrr.io/cran/spFSR/man/spFeatureSelection.html

# Get the importance ranks of best performing features
getImportance(spsaMod1)
RFplot <- plotImportance(spsaMod1) #Doorslaapprob + Vochthandvoet

getImportance(spsaMod2)
LRplot <- plotImportance(spsaMod2) #Wisselendestemming + Piekeren + Pijngewrichten

getImportance(spsaMod3)
KNNplot <- plotImportance(spsaMod3) #Vocht + Pijnspieren 

getImportance(spsaMod4)
SVMplot <- plotImportance(spsaMod4) #Vochthandvoet + Pijnspieren

save(spsaMod1, spsaMod2, spsaMod3, spsaMod4, file="SPSA.Rdata")
load("SPSA.Rdata")
```

